import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { useAtom } from "jotai";
import { useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faFilter, faArrowLeft, faHamburger } from '@fortawesome/free-solid-svg-icons'

import styles from '../styles/Header.module.css'
import { pastaFilterAtom } from "./atoms";

const Header = (props) => {
    
  const [filterClicked, setFilterClicked] = useState(false)
  const [_pastaFilter, setPastaFilter] = useAtom(pastaFilterAtom)

  const filterClickedHandler = () => {
    setFilterClicked(p => p = !p)
  }

  const filterHandler = (selection:string) => {
    setPastaFilter("fuck")
    setPastaFilter(selection)
  }

  const router = useRouter()
  const { route } = router

  return(
    <>
      <Head >
        <title style={{width: "100px", height: "100px"}}>{props.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <span className={styles.container}>

{/* left bumper */}
        <motion.div 
          layoutId="widget" 
          className={styles["container-left"]}
        >    
{/* icon 1 */}
          <div className={styles["container-icon"]}>
            <AnimatePresence exitBeforeEnter>
            {
              route === "/pasta/[id]" ?
              
              <motion.div 
                key={`${route}`}
                initial={{scale: 0}} 
                animate={{scale: [0, 1.20, 1]}}
                exit={{scale: 0}}
              >
                <Link href="/">
                  <a>
                    <FontAwesomeIcon 
                      className={styles["fa-icon"]} 
                      icon={faArrowLeft}
                    />
                  </a>
                </Link>
              </motion.div>
         
              :
          
              <motion.div
                onClick={filterClickedHandler}
                key={`${route}`}
                initial={{scale: 0}} 
                animate={{scale: [0, 1.20, 1]}}
                exit={{scale: 0}}
              >
                <FontAwesomeIcon 
                  className={styles["fa-icon"]} 
                  icon={faFilter}
                />
              </motion.div>
            }
            </AnimatePresence>
        
          </div>

{/* pop-up filter */}
          <AnimatePresence>
          {
            filterClicked &&
              <motion.div
                initial={{scale: 0}}
                animate={{scale: 1}}
                exit={{scale:0}}
                style={{position: "relative", width: "0px", zIndex: 1}}
              >
                <div className={styles["card-filter"]}>
                  <div className={styles["filter-dismiss-container"]}>
                    <div 
                      onClick={filterClickedHandler} 
                      className={styles["filter-dismiss"]}
                    >
                      x
                    </div>
                  </div>
                    <div className={styles["filter-selection-container"]}>
                      <motion.div 
                        whileHover={{scale: 1.2}} 
                        className={styles["filter-selection"]} 
                        onClick={() => filterHandler('short')}>
                          Short
                      </motion.div>
                      <motion.div 
                        whileHover={{scale: 1.2}} 
                        className={styles["filter-selection"]} 
                        onClick={() => filterHandler('long')}>
                          Long
                      </motion.div>  
                      <motion.div 
                        whileHover={{scale: 1.2}} 
                        className={styles["filter-selection"]} 
                        onClick={() => filterHandler('soup')}>
                          Soup
                      </motion.div>  
                      <motion.div 
                        whileHover={{scale: 1.2}} 
                        className={styles["filter-selection"]} 
                        onClick={() => filterHandler('')}>
                          Clear
                      </motion.div>  
                    </div>
                </div>
              </motion.div>
          }
          </AnimatePresence>
        </motion.div>

{/* title */}
        <h1 >
          <div className={`${styles.title} ${styles.textfocusin} display: inline`}>
            Pasta!
          </div>
        </h1>
        
{/* right bumper */}
        <motion.div className={styles["container-right"]}>
          
{/* icon1 */}
          <div className={styles["container-icon"]}>
            <FontAwesomeIcon 
              className={styles["fa-icon"]} 
              icon={faHamburger}
            />
          </div>
        </motion.div>
      </span>
    </>
  )
}

export default Header