import { GetStaticPaths, GetStaticProps } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useRouter } from 'next/router'
import styles from '../../styles/Pasta.module.css'
import Client from 'shopify-buy'


const Pasta = ({product}) => {
  console.log('PRODUCT', product)
  const router = useRouter()
  const { id } = router.query
  return (
    <>
    <div className={styles.container}>
      <Head>
        <title>Pasta: {` ${product.title}`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
          <h1>
            <a className={`${styles.title} ${styles.textfocusin} display: inline`} href="https://nextjs.org">{product.title}</a>
          </h1>

          <Link href="/">
            <a style={{marginLeft: "2rem", padding: "5px 10px", borderRadius: "5px", backgroundColor: "purple", color: "white", cursor: "pointer", alignSelf: "flex-start", fontSize: "30px"}}>&#x2B05;</a>
          </Link>

        <div className={styles.card}>
          <div className={styles.grid}>
            <div 
            className={styles.gridImage}
            style={{ 
              position: 'relative',

              left: '50%',
              transform: "translateX(-50%)",
              width: '400px', 
              height: '240px', 
              margin: '0px', 
              padding: '0px', 
              overflow: 'hidden', 
              boxShadow: '0 0 20px 5px #b8b8b8',
              borderRadius: '10px',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              alignSelf: 'center',
              justifySelf:'center',
              marginTop: '30px',
              marginBottom: '45px'
            }}>
              <Image placeholder='blur' blurDataURL={product.images[0].src} layout='fill' className={styles.cardImage} src={product.images[0].src}/>
            </div>
            <p className={styles.gridDescription} style={{ margin: '15px' }}>
              {product.description}
            </p>
            <div className={styles.gridCheckout}>CHeckout Area</div>
          </div>
        </div>
        </main>
    </div>
    </>
  )
}

export const getStaticProps: GetStaticProps = async({params}) => {
  console.log('params', params)
  const client = Client.buildClient({
    domain: process.env.REACT_APP_SHOPIFY_DOMAIN, 
    storefrontAccessToken: process.env.REACT_APP_SHOPIFY_API 
  })

  let response = await client.product.fetch(params.id)
  let product = response
    // Do something with the product
    console.log(product.id);
    console.log(product.description);
    console.log('fuckingPRODUCT', product);

  return {
    props: {
      product: JSON.parse(JSON.stringify(product))
    },
  }
}

export const getStaticPaths: GetStaticPaths = async() => {
  
  const client = Client.buildClient({
    domain: process.env.REACT_APP_SHOPIFY_DOMAIN,
    storefrontAccessToken: process.env.REACT_APP_SHOPIFY_API
  })
    
  let response = await client.product.fetchAll()
  let products = response
    
  let productIds = products.map(i => i.id)
  console.log('Product Ids', productIds)

  const paths = productIds.map((id) => ({ params: { id: id.toString() } }));

  return {
    paths,
    fallback: false
  }
}

export default Pasta